# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main
  
variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: self-raspberry0201
    steps:
   #   - task: Docker@2
   #     displayName: Build an image
   #     inputs:
   #       command: 'build'
   #       Dockerfile: '**/Dockerfile'
   #       tags: '$(tag)'

      - task: Docker@2
        inputs:
          containerRegistry: 'mydocker0207'
          repository: 'mycarrie0207/scenery'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'